# Datasource: por defecto apunta a Postgres local (Docker), pero en ECS Fargate
# se sobreescribe con variables de entorno inyectadas en la Task Definition
# apuntando al endpoint de Amazon RDS.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/techstore}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

# Amazon SQS - Actividad 2.2 (Auditoria de inventario)
aws.region=${AWS_REGION:us-east-1}
aws.sqs.audit-queue-url=${AWS_SQS_AUDIT_QUEUE_URL:}